### ISSUE TITLE
[Bug] - Unable to see my login fields because of the updated UI kit in Freshdesh. Check screenshot

### ISSUE THREAD

**Issue by usman2023** [freshdesk/crayons#100]
**Describe the bug**
Unable to see my login fields because of the updated UI kit in Freshdesh.

**To Reproduce**
Steps to reproduce the current behavior:

1. Go to 'Apps'
2. Click on 'Settings of Twilio App'
3. Try to 'install the App'
4. See the login fields.

**Expected behavior**
Username and password field should be visible.

**Screenshots**
![Clipboard - June 30, 2020 6_07 PM](https://user-images.githubusercontent.com/68699447/88300617-1f3c1b80-cd1d-11ea-8624-f5db5fa05ce5.png)

**Comment by asifahmedfw** [comment]
@usman2023 Can you use the following script to include crayons? We recommend using the following.
```
<script type="module" src="https://unpkg.com/@freshworks/crayons@2.3/dist/crayons/crayons.esm.js"></script>
<script nomodule src="https://unpkg.com/@freshworks/crayons@2.3/dist/crayons/crayons.js"></script>
```

The recommended way is to use version numbers.
```
<script type="module" src="https://unpkg.com/@freshworks/crayons@<VERSION_NUMBER>/dist/crayons/crayons.esm.js"></script>
<script nomodule src="https://unpkg.com/@freshworks/crayons@<VERSION_NUMBER>/dist/crayons/crayons.js"></script>
```
Where <VERSION_NUMBER> is the version you want to point to.
If you use VERSION_NUMBER = 2, it will point to the latest version in major version 2.
If you use VERSION_NUMBER = 1, it will point to the latest version in major version 1.
If you use VERSION_NUMBER = 2.3, it will point to the latest version in minor version 2.3. -> e.g 2.3.1
If you use VERSION_NUMBER = 2.3.1, it will point to the exact version 2.3.1.

Hope this helps! 👍 

Closing this for now. Please re-open this if the issue persists.

**Comment by owais-techlogix** [comment]
Hi,

I was using these scripts to include crayons

```
<script type="module" src="https://static-dev.freshcloud.io/freshworks-ui-kit/freshworks-ui-kit.esm.js"></script>
<script nomodule src="https://static-dev.freshcloud.io/freshworks-ui-kit/freshworks-ui-kit.js"></script>
```
I replaced it to these scripts

```
<script type="module" src="https://unpkg.com/@freshworks/crayons@2.3/dist/crayons/crayons.esm.js"></script>
<script nomodule src="https://unpkg.com/@freshworks/crayons@2.3/dist/crayons/crayons.js"></script>
```

My above issue resolves but the new issues occur. 
e.g. The toggle button is not working properly. Is that bug? or Is there any documentation that I can use.

Thanks.

**Comment by asifahmedfw** [comment]
@owais-techlogix 
All documents are published at [crayons.freshworks.com](crayons.freshworks.com)
Can you share the exact issue you are facing with the toggle button? Screenshots/Gifs would be of great help. Also, do you see any errors in the console of your browser?
