### ISSUE TITLE
[Bug] - Enable setting multi select component values with multiple values

### ISSUE THREAD

**Issue by shravan-balasubramanian** [freshdesk/crayons#95]
**Component**
Select

**Describe the bug**
Multi select doesn't set multiple values

**To Reproduce**
Steps to reproduce the current behavior:

- Set <fw-select values="[1,2,3]"

**Expected behavior**
1,2,3 values should be selected, but not

**Screenshots**

**Additional context**
Add any other context about the bug here.

**Comment by asifahmedfw** [comment]
This goes against the spec for HTML. 
**Attributes should only be used for scalar values like strings, numbers and boolean values. Properties, on the other hand, are perfectly suited to also hold values that are objects or arrays.**
- https://alligator.io/web-components/attributes-properties/

This can easily be done via properties. Is the attribute absolutely needed?

The worrying part is that if you don't follow the spec, it might break when used in certain frameworks that make assumptions.

**Comment by shravan-balasubramanian** [comment]
> This goes against the spec for HTML.
> **Attributes should only be used for scalar values like strings, numbers and boolean values. Properties, on the other hand, are perfectly suited to also hold values that are objects or arrays.**
> 
> * https://alligator.io/web-components/attributes-properties/
> 
> This can easily be done via properties. Is the attribute absolutely needed?
> 
> The worrying part is that if you don't follow the spec, it might break when used in certain frameworks that make assumptions.

value still remains to be string only. Also I do not mutate the value. Just checking if it is a string array. 🤔
