### ISSUE TITLE
[Bug] - Datepicker not closing when clicked outside of the popup

### ISSUE THREAD

**Issue by nithin-raj** [freshdesk/crayons#98]
**Component**
Datepicker

**Describe the bug**
Datepicker is not closing when clicked outside of the popup.

**To Reproduce**
Steps to reproduce the current behavior:

1. Go to 'https://crayons.freshworks.com/components/datepicker/#usage'
2. Click on 'Single date picker input box'
3. Once the popup is opened, click outside of the popup
4. Popup is not closing

**Expected behavior**
When clicked outside of the popup, it should be closed.

**Screenshots**
https://share.vidyard.com/watch/oKP1WniWeWB6X6iHhfiXp7?

**Comment by asifahmedfw** [comment]
@nithin-raj Thanks for pointing this out. 👍 
@sathishkumar-thangavel Can we take this up?
